export const LOGIN = {
  POST: 'AUTH_LOGIN_POST',
  SUCCESS: 'AUTH_LOGIN_SUCCESS',
  FAILURE: 'AUTH_LOGIN_FAILURE',
}

export const REGISTER = {
  POST: 'AUTH_REGISTER_POST',
  SUCCESS: 'AUTH_REGISTER_SUCCESS',
  FAILURE: 'AUTH_REGISTER_FAILURE',
}

export const LOGOUT = {
  POST: 'AUTH_LOGOUT_POST',
}
