export const DEVELOPER = {
  LIST: 'DEVELOPER_LIST_GET',
  LIST_SUCCESS: 'DEVELOPER_LIST_SUCCESS',
  LIST_FAILURE: 'DEVELOPER_LIST_FAILURE',

  CREATE: 'DEVELOPER_CREATE_GET',
  CREATE_SUCCESS: 'DEVELOPER_CREATE_SUCCESS',
  CREATE_FAILURE: 'DEVELOPER_CREATE_FAILURE',
}
