export const EMPLOYEE = {
  LIST: 'EMPLOYEE_LIST_GET',
  LIST_SUCCESS: 'EMPLOYEE_LIST_SUCCESS',
  LIST_FAILURE: 'EMPLOYEE_LIST_FAILURE',

  CREATE: 'EMPLOYEE_CREATE_GET',
  CREATE_SUCCESS: 'EMPLOYEE_CREATE_SUCCESS',
  CREATE_FAILURE: 'EMPLOYEE_CREATE_FAILURE',
}
