export const PARTICIPANT = {
  LIST: 'PARTICIPANT_LIST_GET',
  LIST_SUCCESS: 'PARTICIPANT_LIST_SUCCESS',
  LIST_FAILURE: 'PARTICIPANT_LIST_FAILURE',

  CREATE: 'PARTICIPANT_CREATE_GET',
  CREATE_SUCCESS: 'PARTICIPANT_CREATE_SUCCESS',
  CREATE_FAILURE: 'PARTICIPANT_CREATE_FAILURE',
}
